# Generated by Django 4.2.1 on 2023-05-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('percent_commission', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
    ]
