# Generated by Django 4.2.1 on 2023-05-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_client_sellers_saleitem_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sellers',
            new_name='Seller',
        ),
    ]
