# Generated by Django 4.2.1 on 2023-05-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_rename_sellers_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='seller',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
