# Generated by Django 4.2.1 on 2023-05-25 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_alter_client_telephone_alter_seller_telephone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='sellers',
            new_name='seller',
        ),
    ]
